### ISSUE TITLE
Data conversion on the fly

### ISSUE THREAD

**Issue by gjniewenhuijse** [snowdd1/homebridge-knx#18] opened 2015-11-23 12:26 UTC
Is it possible to do a data conversion on the fly?

I have a knx garagedoor DPT1: 
0 = closed
1 = open

But the default is DPT5:
0 = open
1 = closed
when i add a "R" after the address, the data is converted to 255,254.. But i want 1 or 0.

```
{
                    "accessory_type": "knxdevice",
                    "description": "sample garage door opener",
                    "name": "Garagedeur",
                    "services": [
                        {
                            "type": "GarageDoorOpener",
                            "name": "Garagedeur",
                            "CurrentDoorState": {
                                "Listen": ["10/1/4"]
                            },
                            "TargetDoorState": {
                                "Set": "10/1/3"
                            }
                        }
                    ]
                }
```

**Comment by snowdd1** [comment] 2015-11-24 14:16
Not yet. The problem is that the garagedooropener uses values 0..4, and that requires at least a byte value.
I have thought about being able to allow individual mappings, but have no working concept yet.
If you have some other logic module on the bus, you might do the mapping there in the meantime; and use a new group address for homekit.

**Comment by gjniewenhuijse** [comment] 2015-11-24 14:47
Individual mappings would be great..
For now its solved by an external logic device.

**Comment by snowdd1** [comment] 2016-10-11 19:02
Hi @gjniewenhuijse Geert-Jan,
you might now have a look at the alpha version of 0.3 - it is branch `plugin-2.0`

**Comment by snowdd1** [comment] 2016-10-11 19:03
Ps: the possibility to write very simple individual handlers should solve this!

**Comment by gjniewenhuijse** [comment] 2016-10-12 13:00
thanks, i try to get that working

**Comment by dlt-** [comment] 2016-10-18 16:28
Converting hue colour to four different KNX group addresses which control r,g,b,w channels of a led strip could also be a good example for 0.3's handler. 
I have now done this by using http-rgb plugin, which just reads and sends values using knxtool, but I think that could be done now by using that custom logic.

**Comment by snowdd1** [comment] 2016-11-04 21:20
Hi @gjniewenhuijse 
Have a look at the sample add-ins that ships with the (now beta) version 0.3.0
E.g. the SimpleGarageDoor I wrote for my garage door, that has only two GAs, one for opening and one for closing:
https://github.com/snowdd1/homebridge-knx/blob/plugin-2.0/lib/addins/SimpleGarageDoor.js

You can install it with `npm install homebridge-knx@beta`

**Closed by snowdd1** 2016-11-04 21:20 UTC
Labels: enhancement
